# Generated by Django 5.0.2 on 2024-02-13 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200)),
                ('phone', models.IntegerField()),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
