# Generated by Django 5.0.2 on 2024-02-14 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hearse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('color', models.TextField(default='black')),
                ('model', models.TextField(default=2016)),
                ('driver_phone', models.IntegerField()),
                ('Price', models.IntegerField(default=0)),
                ('location', models.TextField(default='Nakuru')),
                ('hearse_image', models.ImageField(upload_to='')),
                ('description', models.TextField(default='located in Nakuru')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(default='name', max_length=100)),
                ('From', models.CharField(max_length=100)),
                ('To', models.CharField(max_length=100)),
                ('email', models.EmailField(default='@gmail.com', max_length=100)),
                ('Day', models.DateField(blank=True, null=True)),
                ('time', models.DateTimeField(null=True)),
            ],
        ),
    ]
