# Generated by Django 5.0.2 on 2024-02-14 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hearse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hearse',
            name='hearse_image',
            field=models.ImageField(blank=True, null=True, upload_to='hearse_img/'),
        ),
    ]
