# Generated by Django 5.0.2 on 2024-02-14 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hearse', '0002_alter_hearse_hearse_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
